apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-flask-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-flask-app
  template:
    metadata:
      labels:
        app: argo-flask-app
    spec:
      containers:
<<<<<<< HEAD
        - name: argo-flask-image
          image: 440896245143.dkr.ecr.us-west-2.amazonaws.com/argo-ecr-repo:a65d0fa72a32a0dd6812ae6fb24990f0536b55c8 
=======
        - name: back-end
          image: 440896245143.dkr.ecr.us-west-2.amazonaws.com/argo-ecr-repo:f9245c77c5b3325c66783c9574c8b77afceb623f 
>>>>>>> 4c6216dd4fbbaee63eed31f70737b61c68321ebf
          ports:
            - containerPort: 5000