apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-flask-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-flask-app
  template:
    metadata:
      labels:
        app: argo-flask-app
    spec:
      containers:
        - name: argo-flask-image
          image: 440896245143.dkr.ecr.us-west-2.amazonaws.com/argo-ecr-repo:ef776f6dbc4b0a48f97edc08c53771784eef5567 
          ports:
            - containerPort: 5431